"""Add description field to Transaction

Revision ID: 154343580498
Revises: 17ba6aa7880e
Create Date: 2025-08-27 01:09:34.178663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '154343580498'
down_revision = '17ba6aa7880e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
