"""Added a new column for StudentRegistration Table called is_staff

Revision ID: 1aba96b31476
Revises: 
Create Date: 2025-08-19 21:05:31.369511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1aba96b31476'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_registration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_staff', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_registration', schema=None) as batch_op:
        batch_op.drop_column('is_staff')

    # ### end Alembic commands ###
