"""Set default for is_staff

Revision ID: 66bc80391dba
Revises: 1aba96b31476
Create Date: 2025-08-19 21:06:57.105543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66bc80391dba'
down_revision = '1aba96b31476'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_registration', schema=None) as batch_op:
        batch_op.alter_column('is_staff',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_registration', schema=None) as batch_op:
        batch_op.alter_column('is_staff',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
