"""empty message

Revision ID: 846b1ee2c131
Revises: b0bfaf6a8359
Create Date: 2025-08-25 08:49:26.047251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '846b1ee2c131'
down_revision = 'b0bfaf6a8359'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('issue_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('floor', sa.String(length=3), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('resolved_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_issue_log_resolved_by', 'student_registration', ['resolved_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issue_log', schema=None) as batch_op:
        batch_op.drop_constraint('fk_issue_log_resolved_by', type_='foreignkey')
        batch_op.drop_column('resolved_by')
        batch_op.drop_column('floor')

    # ### end Alembic commands ###
