"""add email in club table

Revision ID: 982e4a7be00c
Revises: 846b1ee2c131
Create Date: 2025-08-25 22:42:09.799524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '982e4a7be00c'
down_revision = '846b1ee2c131'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('club', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=250), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('club', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
