"""added club manager role to student_registration_table

Revision ID: 9e5ef559ec24
Revises: dc93369ece2b
Create Date: 2025-09-02 16:42:57.527758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e5ef559ec24'
down_revision = 'dc93369ece2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_registration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_club_manager', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_registration', schema=None) as batch_op:
        batch_op.drop_column('is_club_manager')

    # ### end Alembic commands ###
