"""noor added new table for issue log

Revision ID: a889717e4b01
Revises: bcc2f4e41efa
Create Date: 2025-08-20 08:27:26.199777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a889717e4b01'
down_revision = 'bcc2f4e41efa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issue_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('floor', sa.String(length=3), nullable=False))
        batch_op.add_column(sa.Column('resolved_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_issue_log_resolved_by', 'student_registration', ['resolved_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issue_log', schema=None) as batch_op:
        batch_op.drop_constraint('fk_issue_log_resolved_by', type_='foreignkey')
        batch_op.drop_column('resolved_by')
        batch_op.drop_column('floor')

    # ### end Alembic commands ###