"""added is_admin column to Student Registration table

Revision ID: bcc2f4e41efa
Revises: fcc917b374af
Create Date: 2025-08-20 01:37:16.185283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcc2f4e41efa'
down_revision = 'fcc917b374af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_registration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_registration', schema=None) as batch_op:
        batch_op.drop_column('is_admin')

    # ### end Alembic commands ###
