"""Refactor IssueLog relationships with FK names

Revision ID: cc01b53e8e6d
Revises: 1ef0851dd792
Create Date: 2025-08-25 05:57:40.469007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc01b53e8e6d'
down_revision = 'b0bfaf6a8359'
branch_labels = None
depends_on = None


def upgrade():
    # Drop temporary table if exists
    op.drop_table('_alembic_tmp_issue_log')

    # Add new columns with temporary server_default for NOT NULL
    with op.batch_alter_table('issue_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'floor',
            sa.String(length=3),
            nullable=False,
            server_default='1'  # default value for existing rows
        ))
        batch_op.add_column(sa.Column('resolved_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_issue_log_resolved_by',
            'student_registration',
            ['resolved_by'],
            ['id']
        )

    # Remove server_default so future inserts require explicit value
    with op.batch_alter_table('issue_log', schema=None) as batch_op:
        batch_op.alter_column('floor', server_default=None)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issue_log', schema=None) as batch_op:
        batch_op.drop_constraint('fk_issue_log_resolved_by', type_='foreignkey')
        batch_op.drop_column('resolved_by')
        batch_op.drop_column('floor')

    op.create_table('_alembic_tmp_issue_log',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('student_id', sa.INTEGER(), nullable=False),
    sa.Column('issue_title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('issue_category', sa.VARCHAR(length=50), nullable=False),
    sa.Column('issue_description', sa.TEXT(), nullable=False),
    sa.Column('location', sa.VARCHAR(length=100), nullable=False),
    sa.Column('priority', sa.VARCHAR(length=20), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=False),
    sa.Column('submitted_at', sa.DATETIME(), nullable=False),
    sa.Column('resolved_at', sa.DATETIME(), nullable=True),
    sa.Column('staff_notes', sa.TEXT(), nullable=True),
    sa.Column('floor', sa.VARCHAR(length=3), nullable=False),
    sa.Column('resolved_by', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['resolved_by'], ['student_registration.id'], name=op.f('fk_issue_log_resolved_by')),
    sa.ForeignKeyConstraint(['student_id'], ['student_registration.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
