"""added is_verified table to student registration table

Revision ID: fcc917b374af
Revises: 66bc80391dba
Create Date: 2025-08-20 00:21:48.400748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcc917b374af'
down_revision = '66bc80391dba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_registration', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=True))
        batch_op.alter_column('is_staff',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_registration', schema=None) as batch_op:
        batch_op.alter_column('is_staff',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.drop_column('is_verified')

    # ### end Alembic commands ###
